sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t chholzer1190/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chholzer1190/docker-react npm run test
